x(tasks): fix format and lint
update to kano v4.3
misc stuff

diff --git a/.kano/tasks/pre_commit b/.kano/tasks/pre_commit
--- a/.kano/tasks/pre_commit
+++ b/.kano/tasks/pre_commit
@@ -11,7 +11,12 @@ pre_commit() {
   _stash_unstaged_files
   _format
   _lint
-  _unstash_unstaged_files
+  if [ $? ]; then
+    _unstash_unstaged_files
+
+  else
+    fail "[pre_commit] linting failed, unstaged changes are still stashed"
+  fi
 }
 
 _stash_unstaged_files() {
